# Generated by Django 5.2.5 on 2025-09-04 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gastos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Gasto')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('data', models.DateField(auto_now=True, verbose_name='Data de Gasto')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('criadoPor', models.CharField(max_length=100, verbose_name='Criado por')),
                ('tipo', models.JSONField(default=['Mercado', 'Farmácia', 'Combustível', 'Casa'], verbose_name='Tipo de Gasto')),
            ],
        ),
    ]
