# Generated by Django 5.2.5 on 2025-09-08 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxocaixa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastos',
            name='tipo',
            field=models.CharField(choices=[('Mercado', 'Mercado'), ('Farmácia', 'Farmácia'), ('Combustível', 'Combustível'), ('Casa', 'Casa')], default='Mercado', max_length=50, verbose_name='Tipo de Gasto'),
        ),
    ]
