# Generated by Django 5.2.5 on 2025-09-08 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxocaixa', '0002_alter_gastos_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastos',
            name='data',
            field=models.DateField(verbose_name='Data de Gasto'),
        ),
    ]
